"""Central config: paths and API endpoints. No secrets here."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
RAW = DATA / "raw"
PROCESSED = DATA / "processed"
for _p in (RAW, PROCESSED):
    _p.mkdir(parents=True, exist_ok=True)

# --- Data sources -----------------------------------------------------------
# martj42 keeps the Kaggle "international results 1872->" dataset mirrored on
# GitHub, so we can pull it with no Kaggle auth.
HISTORICAL_RESULTS_URL = (
    "https://raw.githubusercontent.com/martj42/international_results/master/results.csv"
)

# --- Prediction-market endpoints (public, read-only, no API key) ------------
POLYMARKET_GAMMA = "https://gamma-api.polymarket.com"   # /markets, /events
KALSHI_BASE = "https://external-api.kalshi.com/trade-api/v2"  # /markets, /events, /series/{t}

# --- Modeling knobs ---------------------------------------------------------
# ELO_K is the BASE K applied to qualifier-level matches. Tournament-weighted
# matches scale from this: WC finals → K×1.5 = 60, friendlies → K×0.5 = 20.
# This matches the five-tier scale used by eloratings.net.
ELO_K = 40              # base K (qualifier / Nations League level)
ELO_HOME_ADV = 65       # Elo points added to the non-neutral host
ELO_BASE = 1500         # rating for a team we have never seen
# Annual mean-reversion toward ELO_BASE (FiveThirtyEight SPI methodology).
# At 0.2 a result from 5 years ago retains (0.8)^5 ≈ 33 % of its weight.
# Set to 0.0 to disable (pure sequential Elo with no recency decay).
ELO_MEAN_REVERSION = 0.05
MC_SIMS = 20_000        # Monte-Carlo tournament simulations

# The current tournament's date window. Used by production_elo() to pick out
# in-tournament matches for the goal-difference form adjustment. Previously
# hardcoded separately in the dashboard, which is part of how the deployed
# bot and the dashboard ended up running different models.
CURRENT_WC_START = "2026-06-11"
CURRENT_WC_END = "2026-07-19"

# Calibrated draw model parameters (generated by: python src/models/match_model.py)
DRAW_PARAMS_PATH = PROCESSED / "draw_params.json"

# Tournament "round depth" axis used by the SVI-style survival surface.
# Order matters: deeper round => smaller survival probability (no-arb monotone).
ROUNDS = ["group", "R32", "R16", "QF", "SF", "final", "champion"]
